package com.ciudad.dominio;

// Generated 08-sep-2014 21:11:24 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EstudianteId generated by hbm2java
 */
@Embeddable
public class EstudianteId implements java.io.Serializable {

	private long idestudiante;
	private String tipodoc;

	public EstudianteId() {
	}

	public EstudianteId(long idestudiante) {
		this.idestudiante = idestudiante;
	}

	public EstudianteId(long idestudiante, String tipodoc) {
		this.idestudiante = idestudiante;
		this.tipodoc = tipodoc;
	}

	@Column(name = "idestudiante", nullable = false)
	public long getIdestudiante() {
		return this.idestudiante;
	}

	public void setIdestudiante(long idestudiante) {
		this.idestudiante = idestudiante;
	}

	@Column(name = "tipodoc", length = 2)
	public String getTipodoc() {
		return this.tipodoc;
	}

	public void setTipodoc(String tipodoc) {
		this.tipodoc = tipodoc;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EstudianteId))
			return false;
		EstudianteId castOther = (EstudianteId) other;

		return (this.getIdestudiante() == castOther.getIdestudiante())
				&& ((this.getTipodoc() == castOther.getTipodoc()) || (this
						.getTipodoc() != null && castOther.getTipodoc() != null && this
						.getTipodoc().equals(castOther.getTipodoc())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getIdestudiante();
		result = 37 * result
				+ (getTipodoc() == null ? 0 : this.getTipodoc().hashCode());
		return result;
	}

}
