package com.ciudad.dominio;

// Generated 08-sep-2014 21:11:24 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Estudiante generated by hbm2java
 */
@Entity
@Table(name = "estudiante", schema = "public")
public class Estudiante implements java.io.Serializable {

	private EstudianteId id;

	public Estudiante() {
	}

	public Estudiante(EstudianteId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idestudiante", column = @Column(name = "idestudiante", nullable = false)),
			@AttributeOverride(name = "tipodoc", column = @Column(name = "tipodoc", length = 2)) })
	public EstudianteId getId() {
		return this.id;
	}

	public void setId(EstudianteId id) {
		this.id = id;
	}

}
